// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function OptionLabel(Props) {
  var option = Props.option;
  return React.createElement("div", undefined, React.createElement("span", {
                  className: "fi fi-" + option.value
                }), option.label);
}

var make = OptionLabel;

export {
  make ,
  
}
/* react Not a pure module */
