// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var CountrySelect = require("./CountrySelect.bs.js");

function App(Props) {
  var match = React.useState(function () {
        return "us";
      });
  return React.createElement("div", {
              className: "app"
            }, React.createElement(CountrySelect.make, {
                  country: match[0],
                  className: "country-select"
                }));
}

var make = App;

exports.make = make;
/* react Not a pure module */
