// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("rescript/lib/js/curry.js");
var React = require("react");
var Js_json = require("rescript/lib/js/js_json.js");

function App(Props) {
  React.useState(function () {
        return [];
      });
  var match = React.useState(function () {
        return "";
      });
  var setState = match[1];
  React.useEffect((function () {
          var __x = fetch(" https://gist.githubusercontent.com/rusty-key/659db3f4566df459bd59c8a53dc9f71f/raw/4127f9550ef063121c564025f6d27dceeb279623/counties.json");
          var __x$1 = __x.then(function (prim) {
                return prim.json();
              });
          __x$1.then(function (json) {
                var arr = Js_json.decodeArray(json);
                if (arr !== undefined) {
                  Curry._1(setState, (function (_prev) {
                          return "sucess";
                        }));
                } else {
                  Curry._1(setState, (function (_prev) {
                          return "error";
                        }));
                }
                console.log(arr);
                return Promise.resolve(undefined);
              });
          
        }), []);
  return React.createElement("div", undefined, React.createElement("p", undefined, "Hello World!!!"), React.createElement("p", undefined, match[0]));
}

var make = App;

exports.make = make;
/* react Not a pure module */
