// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Api = require("./Api.bs.js");
var Curry = require("rescript/lib/js/curry.js");
var React = require("react");
var $$Promise = require("@ryyppy/rescript-promise/src/Promise.bs.js");

function App(Props) {
  var match = React.useState(function () {
        return [];
      });
  var setCountrySelects = match[1];
  var match$1 = React.useState(function () {
        return "";
      });
  React.useEffect((function () {
          $$Promise.$$catch(Api.Country.getCountries(undefined).then(function (result) {
                    var tmp;
                    if (result.TAG === /* Ok */0) {
                      var countries = result._0;
                      tmp = Curry._1(setCountrySelects, (function (_prev) {
                              return countries;
                            }));
                    } else {
                      console.log("Could not query countries: " + result._0);
                      tmp = undefined;
                    }
                    return Promise.resolve(tmp);
                  }), (function (e) {
                  if (e.RE_EXN_ID === Api.FailedRequest) {
                    console.log("Operation failed! " + e._1);
                  } else {
                    console.log("Unknown error");
                  }
                  return Promise.resolve(undefined);
                }));
          
        }), []);
  return React.createElement("div", undefined, React.createElement("p", undefined, "Hello World!!!123"), React.createElement("p", undefined, match$1[0]));
}

var make = App;

exports.make = make;
/* react Not a pure module */
