// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ReactSelect = require("react-select").default;

var ReactSelect$1 = {};

function CountrySelect(Props) {
  var value = Props.value;
  var options = Props.options;
  return React.createElement(ReactSelect, {
              value: value,
              options: options
            });
}

var make = CountrySelect;

exports.ReactSelect = ReactSelect$1;
exports.make = make;
/* react Not a pure module */
