// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Css from "@emotion/css";

var option = Css.css({
      display: "flex",
      gap: "8px",
      width: "100%",
      height: "100%",
      color: "#333333",
      alignItems: "center",
      paddingLeft: 9,
      paddingRight: 16,
      textOverflow: "ellipsis",
      overflow: "hidden",
      whiteSpace: "nowrap",
      "&:hover": {
        backgroundColor: "#eeeeee",
        whiteSpace: "normal"
      }
    });

var focused = Css.css({
      backgroundColor: "#eeeeee",
      whiteSpace: "normal"
    });

var selected = Css.css({
      backgroundColor: "#dddddd",
      whiteSpace: "normal"
    });

var flag = Css.css({
      ".fi&": {
        width: "14px",
        height: "10px"
      }
    });

var Styles = {
  option: option,
  focused: focused,
  selected: selected,
  flag: flag
};

function CountrySelectOption(Props) {
  var option$1 = Props.option;
  var innerProps = Props.innerProps;
  var isFocused = Props.isFocused;
  var isSelected = Props.isSelected;
  return React.createElement("div", {
              className: Css.cx([
                    option,
                    isFocused ? focused : "",
                    isSelected ? selected : ""
                  ]),
              id: innerProps.id,
              tabIndex: innerProps.tabIndex,
              onClick: innerProps.onClick
            }, React.createElement("span", {
                  className: "fi fi-" + option$1.value + " " + flag
                }), React.createElement("span", undefined, option$1.label));
}

var make = CountrySelectOption;

export {
  Styles ,
  make ,
  
}
/* option Not a pure module */
