// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";
import * as Caml_array from "rescript/lib/es6/caml_array.js";
import * as Css from "@emotion/css";
import * as ReactWindow from "react-window";

var list = Css.css({
      "&:hover": {
        cursor: "pointer"
      }
    });

var listItem = Css.css({
      display: "flex",
      alignItems: "center",
      justifyContent: "flex-start"
    });

var Styles = {
  list: list,
  listItem: listItem
};

function CountrySelectMenu$Row(Props) {
  var style = Props.style;
  var children = Props.children;
  return React.createElement("div", {
              className: listItem,
              style: style
            }, children);
}

var Row = {
  make: CountrySelectMenu$Row
};

function CountrySelectMenu(Props) {
  var height = Props.height;
  var itemSize = Props.itemSize;
  var menuProps = Props.menuProps;
  var listRef = Props.listRef;
  var childrenArray = React.Children.toArray(menuProps.children);
  var value = Curry._1(menuProps.getValue, undefined);
  var tmp;
  if (value == null) {
    tmp = 0;
  } else {
    console.log(value);
    var index = menuProps.options.findIndex(function (option) {
          return option.value === Caml_array.get(value, 0).value;
        });
    tmp = index !== 0 ? Math.imul(index, 26) : 0;
  }
  return React.createElement(ReactWindow.FixedSizeList, {
              height: height,
              itemSize: itemSize,
              itemCount: childrenArray.length,
              children: (function (param) {
                  var index = param.index;
                  return React.createElement(CountrySelectMenu$Row, {
                              style: param.style,
                              children: Caml_array.get(childrenArray, index),
                              key: index.toString()
                            });
                }),
              className: list,
              itemData: menuProps.focusedOption,
              ref: listRef,
              initialScrollOffset: tmp
            });
}

var make = CountrySelectMenu;

export {
  Styles ,
  Row ,
  make ,
  
}
/* list Not a pure module */
