// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from 'react';
import * as Caml_array from 'rescript/lib/es6/caml_array.js';
import * as Css from '@emotion/css';
import * as ReactWindow from 'react-window';

var list = Css.css({
  // border: "1px solid #d9dddd"
});

var listItem = Css.css({
  display: 'flex',
  alignItems: 'center',
  justifyContent: 'flexStart',
});

var Styles = {
  list: list,
  listItem: listItem,
};

function CountrySelectMenu$Row(Props) {
  var style = Props.style;
  var index = Props.index;
  var children = Props.children;
  return React.createElement(
    'div',
    {
      key: index.toString(),
      className: listItem,
      style: style,
    },
    children
  );
}

var Row = {
  make: CountrySelectMenu$Row,
};

function CountrySelectMenu(Props) {
  var height = Props.height;
  var itemSize = Props.itemSize;
  var menuProps = Props.menuProps;
  return React.createElement(ReactWindow.FixedSizeList, {
    height: height,
    itemSize: itemSize,
    itemCount: React.Children.toArray(menuProps.children).length,
    children: function (param) {
      var index = param.index;
      return React.createElement(CountrySelectMenu$Row, {
        style: param.style,
        index: index,
        children: Caml_array.get(
          React.Children.toArray(menuProps.children),
          index
        ),
      });
    },
    className: list,
  });
}

var make = CountrySelectMenu;

export { Styles, Row, make };
/* list Not a pure module */
