// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Css from "@emotion/css";

var buttonStyle = Css.css({
      display: "flex",
      alighItems: "center",
      paddingLeft: 10,
      paddingRight: 10,
      borderRadius: 2,
      border: "1px solid rgba(0, 0, 0, 0.2)",
      backgroundColor: "#ffffff",
      marginBottom: 2
    });

function Button(Props) {
  var text = Props.text;
  var onClick = Props.onClick;
  return React.createElement("div", {
              className: buttonStyle,
              onClick: onClick
            }, React.createElement("span", undefined, text));
}

var make = Button;

export {
  buttonStyle ,
  make ,
  
}
/* buttonStyle Not a pure module */
