// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Css from "@emotion/css";

var blanketStyle = Css.css({
      bottom: 0,
      left: 0,
      top: 0,
      right: 0,
      position: "fixed",
      zIndex: 1
    });

function DropDown$Blanket(Props) {
  var onClick = Props.onClick;
  return React.createElement("div", {
              className: blanketStyle,
              onClick: onClick
            });
}

var Blanket = {
  blanketStyle: blanketStyle,
  make: DropDown$Blanket
};

var dropDown = Css.css({
      position: "relative"
    });

var menu = Css.css({
      backgroundColor: "white",
      borderRadius: 4,
      boxShadow: "0 0 0 1px hsla(218, 50%, 10%, 0.1), 0 4px 11px hsla(218, 50%, 10%, 0.1)",
      marginTop: 8,
      position: "absolute",
      zIndex: 2
    });

var Styles = {
  dropDown: dropDown,
  menu: menu
};

function DropDown(Props) {
  var children = Props.children;
  var isOpen = Props.isOpen;
  var target = Props.target;
  var onClose = Props.onClose;
  return React.createElement("div", {
              className: dropDown
            }, target, isOpen ? React.createElement("div", undefined, React.createElement("div", {
                        className: menu
                      }, children), React.createElement(DropDown$Blanket, {
                        onClick: onClose
                      })) : null);
}

var make = DropDown;

export {
  Blanket ,
  Styles ,
  make ,
  
}
/* blanketStyle Not a pure module */
